import type { ScrapePlatform, ScrapeTier } from "@/generated/prisma/enums";

/**
 * Curated scrape-source registry (Phase 11 research spec). Seeded on first
 * visit to /studio/scraper/sources and re-applied via "Re-seed registry".
 * Merge key: `key` — re-seeding upserts and never downgrades a platform
 * that was already verified live.
 */
export type SeedSource = {
  key: string;
  name: string;
  baseUrl: string;
  tier: ScrapeTier;
  vertical: string;
  country: string;
  platform: ScrapePlatform;
  supply: boolean;
  enabled: boolean;
  notes?: string;
};

const FINGERPRINT_FALLBACK_NOTE =
  "fingerprint at runtime → JSON-LD fallback if not Shopify/Woo";

const PRINT3D_FINGERPRINT_NOTE = "platform via fingerprint/JSON-LD";

export const SEED_SOURCES: SeedSource[] = [
  // ————————— Tier 1 — Owner's list —————————
  {
    key: "sumaiya-resin",
    name: "Sumaiya Resin",
    baseUrl: "https://sumaiyaresin.art",
    tier: "OWNER",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "resin-arts-jaipur",
    name: "Resin Arts Jaipur",
    baseUrl: "https://resinartsjaipur.com",
    tier: "OWNER",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "kanha-kreation",
    name: "Kanha Kreation",
    baseUrl: "https://kanhakreation.com",
    tier: "OWNER",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "saashi",
    name: "Saashi",
    baseUrl: "https://saashi.co.in",
    tier: "OWNER",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: "WordPress/Woo expected — fingerprint confirms at runtime",
  },
  {
    key: "leoberry-gifts",
    name: "Leoberry Gifts",
    baseUrl: "https://leoberrygifts.com",
    tier: "OWNER",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "resinart-in",
    name: "ResinArt.in",
    baseUrl: "https://resinart.in",
    tier: "OWNER",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "woodensure",
    name: "WoodenSure",
    baseUrl: "https://www.woodensure.com",
    tier: "OWNER",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "poonam-shah-art",
    name: "Poonam Shah Art",
    baseUrl: "https://www.poonamshahart.com",
    tier: "OWNER",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: false,
    notes:
      "NO scrapeable catalog (verified: enquiry-only). Do NOT scrape; her category lines are covered by the Phase 11 category structure.",
  },

  // ————————— Tier 2 — Resin goods (India, Shopify) —————————
  {
    key: "resin24",
    name: "Resin24",
    baseUrl: "https://resin24.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "resin-store-surat",
    name: "Resin Store Surat",
    baseUrl: "https://resinstoresurat.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "rabh",
    name: "Rabh",
    baseUrl: "https://rabh.in",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "classyartz",
    name: "ClassyArtz",
    baseUrl: "https://classyartz.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "pacific-resin-art",
    name: "Pacific Resin Art",
    baseUrl: "https://pacificresinart.in",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "craftpriyaa",
    name: "Craftpriyaa",
    baseUrl: "https://craftpriyaa.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "confetti-gifts",
    name: "Confetti Gifts",
    baseUrl: "https://confettigifts.in",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
    notes: "adjacent gifting",
  },

  // ————————— Tier 2 — Resin goods (India, WooCommerce) —————————
  {
    key: "canvas-by-priya",
    name: "Canvas by Priya",
    baseUrl: "https://canvasbypriya.in",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "bantey-banatey",
    name: "Bantey Banatey",
    baseUrl: "https://banteybanatey.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "resin-art-studio",
    name: "Resin Art Studio",
    baseUrl: "https://resinartstudio.in",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "angroos",
    name: "Angroos",
    baseUrl: "https://angroos.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
    notes: "adjacent gifting",
  },

  // ————————— Tier 2 — Resin goods (global, Shopify) —————————
  {
    key: "thunderwood",
    name: "Thunderwood",
    baseUrl: "https://thunderwood.studio",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "GLOBAL",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "hyperiwood",
    name: "Hyperiwood",
    baseUrl: "https://hyperiwood.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "GLOBAL",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "seawave-table",
    name: "Seawave Table",
    baseUrl: "https://seawavetable.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "GLOBAL",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },

  // ————————— Tier 3 — Supplies (huge catalogs, capped runs) —————————
  {
    key: "tulsi-resin",
    name: "Tulsi Resin",
    baseUrl: "https://tulsiresin.com",
    tier: "SUPPLIES",
    vertical: "supplies",
    country: "IN",
    platform: "SHOPIFY",
    supply: true,
    enabled: true,
  },
  {
    key: "letsresin",
    name: "LetsResin",
    baseUrl: "https://letsresin.com",
    tier: "SUPPLIES",
    vertical: "supplies",
    country: "GLOBAL",
    platform: "SHOPIFY",
    supply: true,
    enabled: true,
  },
  {
    key: "justresin",
    name: "JustResin",
    baseUrl: "https://justresin.store",
    tier: "SUPPLIES",
    vertical: "supplies",
    country: "AU",
    platform: "SHOPIFY",
    supply: true,
    enabled: true,
  },
  {
    key: "totalboat",
    name: "TotalBoat",
    baseUrl: "https://totalboat.com",
    tier: "SUPPLIES",
    vertical: "supplies",
    country: "US",
    platform: "SHOPIFY",
    supply: true,
    enabled: true,
  },

  // ————————— Tier 4 — 3D print —————————
  {
    key: "be3dprintshop",
    name: "BE3D Print Shop",
    baseUrl: "https://be3dprintshop.com",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "the-sculpt-studios",
    name: "The Sculpt Studios",
    baseUrl: "https://thesculptstudios.in",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
    notes: "may be gated — verify",
  },
  {
    key: "igstore",
    name: "IGStore",
    baseUrl: "https://igstore.in",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "3dzone",
    name: "3D Zone",
    baseUrl: "https://3dzone.in",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "think3d",
    name: "think3D",
    baseUrl: "https://think3d.in",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "wol3d",
    name: "WOL3D",
    baseUrl: "https://wol3d.com",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: true,
    enabled: true,
  },
  {
    key: "decords",
    name: "Decords",
    baseUrl: "https://decords.com",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "GLOBAL",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: PRINT3D_FINGERPRINT_NOTE,
  },
  {
    key: "eastside-studio",
    name: "Eastside Studio London",
    baseUrl: "https://eastsidestudiolondon.co.uk",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "UK",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: PRINT3D_FINGERPRINT_NOTE,
  },

  // ═══════════════════════════════════════════════════════════════════
  // Phase 12 — expanded research registry (81 additional stores)
  // Independent brand D2C stores only (no marketplaces). Platform is set
  // where research found a clear Shopify/Woo signal; otherwise UNKNOWN so
  // the engine fingerprints it live on the first individual run.
  // ═══════════════════════════════════════════════════════════════════

  // ————————— Resin goods — India —————————
  {
    key: "resineera",
    name: "Resineera",
    baseUrl: "https://resineera.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "my-bageecha",
    name: "myBageecha",
    baseUrl: "https://mybageecha.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "modeco-arts",
    name: "Modeco Arts",
    baseUrl: "https://modecoarts.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "pinkraft",
    name: "PinKraft",
    baseUrl: "https://pinkraft.in",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "hanging-art",
    name: "Hanging Art",
    baseUrl: "https://hangingart.in",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "resin-clocks",
    name: "Resin Clocks",
    baseUrl: "https://resinclocks.in",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "novo-magic",
    name: "Novo Magic",
    baseUrl: "https://novomagic.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "the-next-decor",
    name: "The Next Decor",
    baseUrl: "https://the-next-decor.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "yf-decor",
    name: "YF Decor",
    baseUrl: "https://yfdecor.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "reziwood",
    name: "Reziwood",
    baseUrl: "https://reziwood.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "vilasaa",
    name: "Vilasaa",
    baseUrl: "https://vilasaa.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "artlivo",
    name: "Artlivo",
    baseUrl: "https://artlivo.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "saajawat",
    name: "Saajawat",
    baseUrl: "https://saajawat.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "indian-resin-product",
    name: "Indian Resin Product",
    baseUrl: "https://indianresinproduct.in",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "resin-and-ritesh",
    name: "Resin and Ritesh",
    baseUrl: "https://resinandritesh.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "mt-resin-arts-india",
    name: "MT Resin Arts India",
    baseUrl: "https://mtresinartsindia.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "resinart-co-in",
    name: "Resin Art Co",
    baseUrl: "https://resinart.co.in",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "ms-exim",
    name: "MS EXIM",
    baseUrl: "https://themsexim.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },

  // ————————— Resin goods — global —————————
  {
    key: "epoxy-moxy",
    name: "Epoxy Moxy",
    baseUrl: "https://epoxymoxys.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "epoxyum",
    name: "Epoxyum",
    baseUrl: "https://epoxyum.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "EU",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "upp-home-store",
    name: "UPP Home Store",
    baseUrl: "https://upphomestore.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "chagrin-valley-furniture",
    name: "Chagrin Valley Custom Furniture",
    baseUrl: "https://chagrinvalleycustomfurniture.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "carlberg-design",
    name: "Carlberg Design",
    baseUrl: "https://rustictrip.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "stockton-heritage",
    name: "Stockton Heritage",
    baseUrl: "https://stocktonheritage.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "iv-river-tables",
    name: "IV River Tables",
    baseUrl: "https://ivrivertables.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "rustic-red-door",
    name: "Rustic Red Door",
    baseUrl: "https://rusticreddoor.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "epoxy-rivers",
    name: "Epoxy Rivers",
    baseUrl: "https://epoxyrivers.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "lancaster-live-edge",
    name: "Lancaster Live Edge",
    baseUrl: "https://lancasterliveedge.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "resin-and-rose",
    name: "Resin and Rose",
    baseUrl: "https://resinandrose.co.uk",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "UK",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "resin-society",
    name: "Resin Society",
    baseUrl: "https://resinsociety.net",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "serene-life-art",
    name: "Serene Life Art",
    baseUrl: "https://3dresinpainting.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "sandune",
    name: "Sandune",
    baseUrl: "https://sandune.online",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "UK",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "artist-lisa-marie",
    name: "Artist Lisa Marie",
    baseUrl: "https://artistlisamarie.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "vivid-resin-creation",
    name: "Vivid Resin Creation",
    baseUrl: "https://vividresincreation.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "art-unleashed",
    name: "Art Unleashed",
    baseUrl: "https://artunleashed.us",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "little-hurricane-co",
    name: "Little Hurricane Co",
    baseUrl: "https://littlehurricaneco.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "AU",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "lalka-boutique",
    name: "Lalka Boutique",
    baseUrl: "https://lalka.au",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "AU",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "eucalypse",
    name: "Eucalypse",
    baseUrl: "https://eucalypse.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "AU",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "resins-gift-shop-uk",
    name: "Resins Gift Shop UK",
    baseUrl: "https://resinsgiftshopuk.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "UK",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "pressed-floral",
    name: "Pressed Floral",
    baseUrl: "https://pressedfloral.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "eight-acorns",
    name: "Eight Acorns",
    baseUrl: "https://eightacorns.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "magnolia-studios",
    name: "Magnolia Studios",
    baseUrl: "https://magnoliafloralpreservation.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "smile-with-flower",
    name: "Smile with Flower",
    baseUrl: "https://smilewithflower.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "prescription-resin",
    name: "Prescription Resin",
    baseUrl: "https://prescriptionresin.co.uk",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "UK",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },

  // ————————— Supplies — India —————————
  {
    key: "bohriali",
    name: "BohriAli",
    baseUrl: "https://bohriali.com",
    tier: "SUPPLIES",
    vertical: "supplies",
    country: "IN",
    platform: "SHOPIFY",
    supply: true,
    enabled: true,
  },
  {
    key: "jorshor-store",
    name: "JorShor Store",
    baseUrl: "https://jorshorstore.com",
    tier: "SUPPLIES",
    vertical: "supplies",
    country: "IN",
    platform: "SHOPIFY",
    supply: true,
    enabled: true,
    notes: "dried flowers / preserved botanicals",
  },
  {
    key: "mb-epoxy",
    name: "MB Epoxy",
    baseUrl: "https://mbepoxy.in",
    tier: "SUPPLIES",
    vertical: "supplies",
    country: "IN",
    platform: "SHOPIFY",
    supply: true,
    enabled: true,
  },
  {
    key: "crafteria",
    name: "Crafteria",
    baseUrl: "https://crafteriaindia.com",
    tier: "SUPPLIES",
    vertical: "supplies",
    country: "IN",
    platform: "SHOPIFY",
    supply: true,
    enabled: true,
    notes: "silicone moulds",
  },
  {
    key: "brownwoods4art",
    name: "Brownwoods4art",
    baseUrl: "https://brownwoods4art.com",
    tier: "SUPPLIES",
    vertical: "supplies",
    country: "IN",
    platform: "SHOPIFY",
    supply: true,
    enabled: true,
    notes: "dried flowers / preserved botanicals",
  },
  {
    key: "epoxy-art-india",
    name: "Epoxy Art India",
    baseUrl: "https://epoxyartindia.com",
    tier: "SUPPLIES",
    vertical: "supplies",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: true,
    enabled: true,
  },
  {
    key: "epoxy-resins-india",
    name: "Epoxy Resins India",
    baseUrl: "https://epoxyresins.in",
    tier: "SUPPLIES",
    vertical: "supplies",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: true,
    enabled: true,
  },
  {
    key: "meraki-artencial",
    name: "Meraki Artencial Store",
    baseUrl: "https://merakiartencialstore.com",
    tier: "SUPPLIES",
    vertical: "supplies",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: true,
    enabled: true,
    notes: "moulds + resin jewellery blanks",
  },

  // ————————— Supplies — global —————————
  {
    key: "craft-resin",
    name: "Craft Resin",
    baseUrl: "https://craft-resin.com",
    tier: "SUPPLIES",
    vertical: "supplies",
    country: "US",
    platform: "SHOPIFY",
    supply: true,
    enabled: true,
  },
  {
    key: "baltic-day",
    name: "Baltic Day",
    baseUrl: "https://balticday.com",
    tier: "SUPPLIES",
    vertical: "supplies",
    country: "US",
    platform: "SHOPIFY",
    supply: true,
    enabled: true,
  },
  {
    key: "eye-candy-pigments",
    name: "Eye Candy Pigments",
    baseUrl: "https://eyecandypigments.com",
    tier: "SUPPLIES",
    vertical: "supplies",
    country: "US",
    platform: "SHOPIFY",
    supply: true,
    enabled: true,
  },
  {
    key: "resiners",
    name: "Resiners",
    baseUrl: "https://resiners.com",
    tier: "SUPPLIES",
    vertical: "supplies",
    country: "US",
    platform: "SHOPIFY",
    supply: true,
    enabled: true,
  },
  {
    key: "jeff-mack-supply",
    name: "Jeff Mack Supply",
    baseUrl: "https://jeffmacksupply.com",
    tier: "SUPPLIES",
    vertical: "supplies",
    country: "US",
    platform: "SHOPIFY",
    supply: true,
    enabled: true,
    notes: "silicone moulds",
  },
  {
    key: "apex-resin",
    name: "Apex Resin",
    baseUrl: "https://apexresin.co.uk",
    tier: "SUPPLIES",
    vertical: "supplies",
    country: "UK",
    platform: "SHOPIFY",
    supply: true,
    enabled: true,
  },
  {
    key: "magic-resin",
    name: "Magic Resin",
    baseUrl: "https://magicresin.com",
    tier: "SUPPLIES",
    vertical: "supplies",
    country: "US",
    platform: "UNKNOWN",
    supply: true,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "resin-pro",
    name: "Resin Pro",
    baseUrl: "https://resinpro.eu",
    tier: "SUPPLIES",
    vertical: "supplies",
    country: "EU",
    platform: "WOOCOMMERCE",
    supply: true,
    enabled: true,
  },

  // ————————— 3D print — India —————————
  {
    key: "diy3d",
    name: "DIY3D",
    baseUrl: "https://diy3d.in",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "IN",
    platform: "SHOPIFY",
    supply: true,
    enabled: true,
    notes: "filament / supplies",
  },
  {
    key: "numakers",
    name: "Numakers",
    baseUrl: "https://india.numakers.com",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "IN",
    platform: "SHOPIFY",
    supply: true,
    enabled: true,
    notes: "filament / supplies",
  },
  {
    key: "almighty-fila",
    name: "Almighty Fila",
    baseUrl: "https://almightyfila.com",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "IN",
    platform: "UNKNOWN",
    supply: true,
    enabled: true,
    notes: PRINT3D_FINGERPRINT_NOTE,
  },
  {
    key: "nfil3d",
    name: "Nfil3D",
    baseUrl: "https://nfil3d.com",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "3ding",
    name: "3Ding",
    baseUrl: "https://3ding.in",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: PRINT3D_FINGERPRINT_NOTE,
  },
  {
    key: "3idea",
    name: "3idea Technology",
    baseUrl: "https://3idea.in",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: PRINT3D_FINGERPRINT_NOTE,
  },
  {
    key: "3dselfiy",
    name: "3DSelfiy",
    baseUrl: "https://3dselfiy.com",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: PRINT3D_FINGERPRINT_NOTE,
  },
  {
    key: "layerlabs",
    name: "LayerLabs",
    baseUrl: "https://layerlabs.in",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "tathastu-keepsakes",
    name: "Tathastu Keepsakes",
    baseUrl: "https://tathastukeepsakes.in",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: PRINT3D_FINGERPRINT_NOTE,
  },
  {
    key: "mitrayaa",
    name: "Mitrayaa",
    baseUrl: "https://mitrayaa.com",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },

  // ————————— 3D print — global —————————
  {
    key: "atomic-filament",
    name: "Atomic Filament",
    baseUrl: "https://atomicfilament.com",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "US",
    platform: "SHOPIFY",
    supply: true,
    enabled: true,
    notes: "filament / supplies",
  },
  {
    key: "coex-3d",
    name: "COEX 3D",
    baseUrl: "https://coex3d.com",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "US",
    platform: "SHOPIFY",
    supply: true,
    enabled: true,
    notes: "filament / supplies",
  },
  {
    key: "matterhackers",
    name: "MatterHackers",
    baseUrl: "https://matterhackers.com",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "US",
    platform: "UNKNOWN",
    supply: true,
    enabled: true,
    notes: PRINT3D_FINGERPRINT_NOTE,
  },
  {
    key: "west3d",
    name: "West3D",
    baseUrl: "https://west3d.com",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "US",
    platform: "SHOPIFY",
    supply: true,
    enabled: true,
    notes: "printer parts / supplies",
  },
  {
    key: "micro-swiss",
    name: "Micro Swiss",
    baseUrl: "https://store.micro-swiss.com",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "US",
    platform: "SHOPIFY",
    supply: true,
    enabled: true,
    notes: "printer parts / supplies",
  },
  {
    key: "filamentive",
    name: "Filamentive",
    baseUrl: "https://filamentive.com",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "UK",
    platform: "WOOCOMMERCE",
    supply: true,
    enabled: true,
    notes: "filament / supplies",
  },
  {
    key: "3d-printz",
    name: "3D Printz",
    baseUrl: "https://3dprintz.co.uk",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "UK",
    platform: "UNKNOWN",
    supply: true,
    enabled: true,
    notes: PRINT3D_FINGERPRINT_NOTE,
  },
  {
    key: "3dqf",
    name: "3DQF",
    baseUrl: "https://3dqf.co.uk",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "UK",
    platform: "UNKNOWN",
    supply: true,
    enabled: true,
    notes: PRINT3D_FINGERPRINT_NOTE,
  },
  {
    key: "flexifriends3d",
    name: "FlexiFriends3D",
    baseUrl: "https://flexifriends3d.com",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
    notes: "3D-printed art / figures",
  },
  {
    key: "jollifrogs",
    name: "Jollifrogs",
    baseUrl: "https://jollifrogs.com",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "AU",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
    notes: "3D-printed art / figures",
  },
  {
    key: "trexy3d",
    name: "Trexy3D",
    baseUrl: "https://trexy3d.com",
    tier: "PRINT3D",
    vertical: "3dprint",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
    notes: "3D-printed art / figures",
  },
];
