import type { Prisma } from "@/generated/prisma/client";
import type {
  CollectionMode,
  ScrapePlatform,
  ScrapeTier,
} from "@/generated/prisma/enums";

/**
 * Curated scrape-source registry (Phase 11 research spec). Seeded on first
 * visit to /studio/scraper/sources and re-applied via "Re-seed registry".
 * Merge key: `key` — re-seeding upserts and never downgrades a platform
 * that was already verified live.
 */
export type SeedSource = {
  key: string;
  name: string;
  baseUrl: string;
  tier: ScrapeTier;
  vertical: string;
  country: string;
  platform: ScrapePlatform;
  supply: boolean;
  enabled: boolean;
  notes?: string;
  /**
   * Governance, for the rows where the registry itself already records a
   * decision. Applied on CREATE only — like `enabled`, an operator's later
   * choice in the Studio outranks the seed and must survive a re-seed.
   * Omitted means HTTP, the schema default.
   */
  collectionMode?: CollectionMode;
};

/** The row as it exists today, or undefined when this seed is new. */
export type SeedSourceCurrent =
  | { platform: ScrapePlatform; verifiedAt: Date | null }
  | undefined;

/**
 * The upsert payload for one seed — the ONE definition of what re-seeding
 * writes.
 *
 * It lives in this db-free module because TWO callers reconcile the registry
 * and they must not drift: `applySeedSources` (the Studio's "Re-seed registry"
 * button) and `prisma/seed-sources.ts` (the deploy-time script bootstrap runs
 * on every build, which cannot import the Studio one because that pulls in
 * `@/lib/db`). The second used to be a hand-copy of the first under a comment
 * promising it "mirrors applySeedSources exactly". It stopped being true the
 * moment `collectionMode` was added to one of them: a fresh deploy seeded the
 * enquiry-only source as automatable, and only CI's clean database caught it —
 * a developer database already had the row, so the migration's backfill hid
 * the bug locally.
 *
 * WHAT THE UPDATE BRANCH DELIBERATELY OMITS is the whole rule: `enabled`,
 * `collectionMode` and every policy-review column. Those are the operator's
 * decisions, and a deploy that runs on every build must never overwrite one.
 * A seed's `collectionMode` therefore applies on CREATE only — it records what
 * the registry already knew about a brand-new row, not an opinion to re-impose
 * on an existing one.
 */
export function seedSourceUpsertData(
  seed: SeedSource,
  current: SeedSourceCurrent,
): {
  create: Prisma.ScrapeSourceCreateInput;
  update: Prisma.ScrapeSourceUpdateInput;
} {
  // A platform confirmed against the live site outranks the seed's guess.
  const keepVerifiedPlatform =
    current !== undefined &&
    current.verifiedAt !== null &&
    current.platform !== "UNKNOWN";

  return {
    create: {
      key: seed.key,
      name: seed.name,
      baseUrl: seed.baseUrl,
      tier: seed.tier,
      vertical: seed.vertical,
      country: seed.country,
      platform: seed.platform,
      supply: seed.supply,
      enabled: seed.enabled,
      notes: seed.notes ?? null,
      ...(seed.collectionMode ? { collectionMode: seed.collectionMode } : {}),
    },
    update: {
      name: seed.name,
      baseUrl: seed.baseUrl,
      tier: seed.tier,
      vertical: seed.vertical,
      country: seed.country,
      supply: seed.supply,
      ...(seed.notes !== undefined ? { notes: seed.notes } : {}),
      ...(keepVerifiedPlatform ? {} : { platform: seed.platform }),
    },
  };
}

const FINGERPRINT_FALLBACK_NOTE =
  "fingerprint at runtime → JSON-LD fallback if not Shopify/Woo";

export const SEED_SOURCES: SeedSource[] = [
  // ————————— Tier 1 — Owner's list —————————
  {
    key: "sumaiya-resin",
    name: "Sumaiya Resin",
    baseUrl: "https://sumaiyaresin.art",
    tier: "OWNER",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "resin-arts-jaipur",
    name: "Resin Arts Jaipur",
    baseUrl: "https://resinartsjaipur.com",
    tier: "OWNER",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "kanha-kreation",
    name: "Kanha Kreation",
    baseUrl: "https://kanhakreation.com",
    tier: "OWNER",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "saashi",
    name: "Saashi",
    baseUrl: "https://saashi.co.in",
    tier: "OWNER",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: "WordPress/Woo expected — fingerprint confirms at runtime",
  },
  {
    key: "leoberry-gifts",
    name: "Leoberry Gifts",
    baseUrl: "https://leoberrygifts.com",
    tier: "OWNER",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "resinart-in",
    name: "ResinArt.in",
    baseUrl: "https://resinart.in",
    tier: "OWNER",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "woodensure",
    name: "WoodenSure",
    baseUrl: "https://www.woodensure.com",
    tier: "OWNER",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "poonam-shah-art",
    name: "Poonam Shah Art",
    baseUrl: "https://www.poonamshahart.com",
    tier: "OWNER",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: false,
    collectionMode: "MANUAL_RESEARCH",
    notes:
      "NO scrapeable catalog (verified: enquiry-only). Do NOT scrape; her category lines are covered by the Phase 11 category structure.",
  },

  // ————————— Tier 2 — Resin goods (India, Shopify) —————————
  {
    key: "resin24",
    name: "Resin24",
    baseUrl: "https://resin24.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "resin-store-surat",
    name: "Resin Store Surat",
    baseUrl: "https://resinstoresurat.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "rabh",
    name: "Rabh",
    baseUrl: "https://rabh.in",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "classyartz",
    name: "ClassyArtz",
    baseUrl: "https://classyartz.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "pacific-resin-art",
    name: "Pacific Resin Art",
    baseUrl: "https://pacificresinart.in",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "craftpriyaa",
    name: "Craftpriyaa",
    baseUrl: "https://craftpriyaa.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "confetti-gifts",
    name: "Confetti Gifts",
    baseUrl: "https://confettigifts.in",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
    notes: "adjacent gifting",
  },

  // ————————— Tier 2 — Resin goods (India, WooCommerce) —————————
  {
    key: "canvas-by-priya",
    name: "Canvas by Priya",
    baseUrl: "https://canvasbypriya.in",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "bantey-banatey",
    name: "Bantey Banatey",
    baseUrl: "https://banteybanatey.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "resin-art-studio",
    name: "Resin Art Studio",
    baseUrl: "https://resinartstudio.in",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "angroos",
    name: "Angroos",
    baseUrl: "https://angroos.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
    notes: "adjacent gifting",
  },

  // ————————— Tier 2 — Resin goods (global, Shopify) —————————
  {
    key: "thunderwood",
    name: "Thunderwood",
    baseUrl: "https://thunderwood.studio",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "GLOBAL",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "hyperiwood",
    name: "Hyperiwood",
    baseUrl: "https://hyperiwood.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "GLOBAL",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "seawave-table",
    name: "Seawave Table",
    baseUrl: "https://seawavetable.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "GLOBAL",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },

  // ═══════════════════════════════════════════════════════════════════
  // Phase 12 — expanded research registry (49 additional stores; it was 81
  // before the 2026-09-15 re-focus removed the supplies and 3D-print tiers)
  // Independent brand D2C stores only (no marketplaces). Platform is set
  // where research found a clear Shopify/Woo signal; otherwise UNKNOWN so
  // the engine fingerprints it live on the first individual run.
  // ═══════════════════════════════════════════════════════════════════

  // ————————— Resin goods — India —————————
  {
    key: "resineera",
    name: "Resineera",
    baseUrl: "https://resineera.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "my-bageecha",
    name: "myBageecha",
    baseUrl: "https://mybageecha.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "modeco-arts",
    name: "Modeco Arts",
    baseUrl: "https://modecoarts.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "pinkraft",
    name: "PinKraft",
    baseUrl: "https://pinkraft.in",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "hanging-art",
    name: "Hanging Art",
    baseUrl: "https://hangingart.in",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "resin-clocks",
    name: "Resin Clocks",
    baseUrl: "https://resinclocks.in",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "novo-magic",
    name: "Novo Magic",
    baseUrl: "https://novomagic.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "the-next-decor",
    name: "The Next Decor",
    baseUrl: "https://the-next-decor.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "yf-decor",
    name: "YF Decor",
    baseUrl: "https://yfdecor.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "reziwood",
    name: "Reziwood",
    baseUrl: "https://reziwood.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "vilasaa",
    name: "Vilasaa",
    baseUrl: "https://vilasaa.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "artlivo",
    name: "Artlivo",
    baseUrl: "https://artlivo.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "saajawat",
    name: "Saajawat",
    baseUrl: "https://saajawat.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "indian-resin-product",
    name: "Indian Resin Product",
    baseUrl: "https://indianresinproduct.in",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "resin-and-ritesh",
    name: "Resin and Ritesh",
    baseUrl: "https://resinandritesh.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "mt-resin-arts-india",
    name: "MT Resin Arts India",
    baseUrl: "https://mtresinartsindia.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "resinart-co-in",
    name: "Resin Art Co",
    baseUrl: "https://resinart.co.in",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "ms-exim",
    name: "MS EXIM",
    baseUrl: "https://themsexim.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "IN",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },

  // ————————— Resin goods — global —————————
  {
    key: "epoxy-moxy",
    name: "Epoxy Moxy",
    baseUrl: "https://epoxymoxys.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "epoxyum",
    name: "Epoxyum",
    baseUrl: "https://epoxyum.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "EU",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "upp-home-store",
    name: "UPP Home Store",
    baseUrl: "https://upphomestore.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "chagrin-valley-furniture",
    name: "Chagrin Valley Custom Furniture",
    baseUrl: "https://chagrinvalleycustomfurniture.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "carlberg-design",
    name: "Carlberg Design",
    baseUrl: "https://rustictrip.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "stockton-heritage",
    name: "Stockton Heritage",
    baseUrl: "https://stocktonheritage.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "iv-river-tables",
    name: "IV River Tables",
    baseUrl: "https://ivrivertables.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "rustic-red-door",
    name: "Rustic Red Door",
    baseUrl: "https://rusticreddoor.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "epoxy-rivers",
    name: "Epoxy Rivers",
    baseUrl: "https://epoxyrivers.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "lancaster-live-edge",
    name: "Lancaster Live Edge",
    baseUrl: "https://lancasterliveedge.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "WOOCOMMERCE",
    supply: false,
    enabled: true,
  },
  {
    key: "resin-and-rose",
    name: "Resin and Rose",
    baseUrl: "https://resinandrose.co.uk",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "UK",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "resin-society",
    name: "Resin Society",
    baseUrl: "https://resinsociety.net",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "serene-life-art",
    name: "Serene Life Art",
    baseUrl: "https://3dresinpainting.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "sandune",
    name: "Sandune",
    baseUrl: "https://sandune.online",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "UK",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "artist-lisa-marie",
    name: "Artist Lisa Marie",
    baseUrl: "https://artistlisamarie.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "vivid-resin-creation",
    name: "Vivid Resin Creation",
    baseUrl: "https://vividresincreation.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "art-unleashed",
    name: "Art Unleashed",
    baseUrl: "https://artunleashed.us",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "little-hurricane-co",
    name: "Little Hurricane Co",
    baseUrl: "https://littlehurricaneco.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "AU",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "lalka-boutique",
    name: "Lalka Boutique",
    baseUrl: "https://lalka.au",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "AU",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "eucalypse",
    name: "Eucalypse",
    baseUrl: "https://eucalypse.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "AU",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "resins-gift-shop-uk",
    name: "Resins Gift Shop UK",
    baseUrl: "https://resinsgiftshopuk.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "UK",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "pressed-floral",
    name: "Pressed Floral",
    baseUrl: "https://pressedfloral.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "eight-acorns",
    name: "Eight Acorns",
    baseUrl: "https://eightacorns.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "magnolia-studios",
    name: "Magnolia Studios",
    baseUrl: "https://magnoliafloralpreservation.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "SHOPIFY",
    supply: false,
    enabled: true,
  },
  {
    key: "smile-with-flower",
    name: "Smile with Flower",
    baseUrl: "https://smilewithflower.com",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "US",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
  {
    key: "prescription-resin",
    name: "Prescription Resin",
    baseUrl: "https://prescriptionresin.co.uk",
    tier: "RESIN_GOODS",
    vertical: "resin",
    country: "UK",
    platform: "UNKNOWN",
    supply: false,
    enabled: true,
    notes: FINGERPRINT_FALLBACK_NOTE,
  },
];
